// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Course struct {
	ID         int64            `json:"id"`
	Title      string           `json:"title"`
	CategoryID int64            `json:"category_id"`
	Week       pgtype.Int4      `json:"week"`
	Duration   string           `json:"duration"`
	Capacity   int32            `json:"capacity"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
}

type CourseCategory struct {
	ID        int64            `json:"id"`
	Name      string           `json:"name"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type User struct {
	ID        int64            `json:"id"`
	Username  string           `json:"username"`
	Password  string           `json:"password"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	Flag      int32            `json:"flag"`
}

type UserCourse struct {
	UserID    int64            `json:"user_id"`
	CourseID  int64            `json:"course_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}
