// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
)

type Querier interface {
	CreateCourse(ctx context.Context, arg CreateCourseParams) (Course, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserCourse(ctx context.Context, arg CreateUserCourseParams) error
	DeleteCourse(ctx context.Context, id int64) error
	DeleteUserCourse(ctx context.Context, arg DeleteUserCourseParams) (int64, error)
	GetCourseByID(ctx context.Context, id int64) (Course, error)
	GetCourseByIDForUpdate(ctx context.Context, id int64) (Course, error)
	GetCoursesByUserID(ctx context.Context, userID int64) ([]Course, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserByIDForUpdate(ctx context.Context, id int64) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	IncrementCapacity(ctx context.Context, id int64) (Course, error)
	ListCourses(ctx context.Context) ([]Course, error)
	ListUsers(ctx context.Context) ([]User, error)
	TryDecrementCapacity(ctx context.Context, id int64) (Course, error)
	UpdateCourse(ctx context.Context, arg UpdateCourseParams) (Course, error)
	UpdateUserFlag(ctx context.Context, arg UpdateUserFlagParams) error
}

var _ Querier = (*Queries)(nil)
