// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
)

type Querier interface {
	CreateCourse(ctx context.Context, arg CreateCourseParams) (Course, error)
	DeleteCourse(ctx context.Context, id int64) error
	GetCourseByID(ctx context.Context, id int64) (Course, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	UpdateCourse(ctx context.Context, arg UpdateCourseParams) (Course, error)
}

var _ Querier = (*Queries)(nil)
