// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCourse = `-- name: CreateCourse :one
INSERT INTO courses (
    title,
    category_id,
    week,
    duration,
    capacity
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING
    id,
    title,
    category_id,
    week,
    duration,
    capacity,
    created_at,
    updated_at
`

type CreateCourseParams struct {
	Title      string      `json:"title"`
	CategoryID int64       `json:"category_id"`
	Week       pgtype.Int4 `json:"week"`
	Duration   string      `json:"duration"`
	Capacity   int32       `json:"capacity"`
}

func (q *Queries) CreateCourse(ctx context.Context, arg CreateCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, createCourse,
		arg.Title,
		arg.CategoryID,
		arg.Week,
		arg.Duration,
		arg.Capacity,
	)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CategoryID,
		&i.Week,
		&i.Duration,
		&i.Capacity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCourse = `-- name: DeleteCourse :exec
DELETE FROM courses
WHERE id = $1
`

func (q *Queries) DeleteCourse(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteCourse, id)
	return err
}

const getCourseByID = `-- name: GetCourseByID :one
SELECT
    id,
    title,
    category_id,
    week,
    duration,
    capacity,
    created_at,
    updated_at
FROM courses
WHERE id = $1
`

func (q *Queries) GetCourseByID(ctx context.Context, id int64) (Course, error) {
	row := q.db.QueryRow(ctx, getCourseByID, id)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CategoryID,
		&i.Week,
		&i.Duration,
		&i.Capacity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password, created_at, updated_at, flag
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Flag,
	)
	return i, err
}

const updateCourse = `-- name: UpdateCourse :one
UPDATE courses
SET
    title = $2,
    category_id = $3,
    week = $4,
    duration = $5,
    capacity = $6,
    updated_at = NOW()
WHERE id = $1
RETURNING
    id,
    title,
    category_id,
    week,
    duration,
    capacity,
    created_at,
    updated_at
`

type UpdateCourseParams struct {
	ID         int64       `json:"id"`
	Title      string      `json:"title"`
	CategoryID int64       `json:"category_id"`
	Week       pgtype.Int4 `json:"week"`
	Duration   string      `json:"duration"`
	Capacity   int32       `json:"capacity"`
}

func (q *Queries) UpdateCourse(ctx context.Context, arg UpdateCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, updateCourse,
		arg.ID,
		arg.Title,
		arg.CategoryID,
		arg.Week,
		arg.Duration,
		arg.Capacity,
	)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CategoryID,
		&i.Week,
		&i.Duration,
		&i.Capacity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
