// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCourse = `-- name: CreateCourse :one
INSERT INTO courses (
    title,
    category_id,
    week,
    duration,
    capacity
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING
    id,
    title,
    category_id,
    week,
    duration,
    capacity,
    created_at,
    updated_at
`

type CreateCourseParams struct {
	Title      string      `json:"title"`
	CategoryID int64       `json:"category_id"`
	Week       pgtype.Int4 `json:"week"`
	Duration   string      `json:"duration"`
	Capacity   int32       `json:"capacity"`
}

func (q *Queries) CreateCourse(ctx context.Context, arg CreateCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, createCourse,
		arg.Title,
		arg.CategoryID,
		arg.Week,
		arg.Duration,
		arg.Capacity,
	)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CategoryID,
		&i.Week,
		&i.Duration,
		&i.Capacity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    username,
    password,
    flag
) VALUES (
    $1, $2, 0
)
RETURNING id, username, password, created_at, updated_at, flag
`

type CreateUserParams struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.Password)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Flag,
	)
	return i, err
}

const createUserCourse = `-- name: CreateUserCourse :exec
INSERT INTO user_courses (user_id, course_id)
VALUES ($1, $2)
`

type CreateUserCourseParams struct {
	UserID   int64 `json:"user_id"`
	CourseID int64 `json:"course_id"`
}

func (q *Queries) CreateUserCourse(ctx context.Context, arg CreateUserCourseParams) error {
	_, err := q.db.Exec(ctx, createUserCourse, arg.UserID, arg.CourseID)
	return err
}

const deleteCourse = `-- name: DeleteCourse :exec
DELETE FROM courses
WHERE id = $1
`

func (q *Queries) DeleteCourse(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteCourse, id)
	return err
}

const deleteUserCourse = `-- name: DeleteUserCourse :execrows
DELETE FROM user_courses
WHERE user_id = $1 AND course_id = $2
`

type DeleteUserCourseParams struct {
	UserID   int64 `json:"user_id"`
	CourseID int64 `json:"course_id"`
}

func (q *Queries) DeleteUserCourse(ctx context.Context, arg DeleteUserCourseParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserCourse, arg.UserID, arg.CourseID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCourseByID = `-- name: GetCourseByID :one
SELECT
    id,
    title,
    category_id,
    week,
    duration,
    capacity,
    created_at,
    updated_at
FROM courses
WHERE id = $1
`

func (q *Queries) GetCourseByID(ctx context.Context, id int64) (Course, error) {
	row := q.db.QueryRow(ctx, getCourseByID, id)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CategoryID,
		&i.Week,
		&i.Duration,
		&i.Capacity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCourseByIDForUpdate = `-- name: GetCourseByIDForUpdate :one
SELECT
    id,
    title,
    category_id,
    week,
    duration,
    capacity,
    created_at,
    updated_at
FROM courses
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetCourseByIDForUpdate(ctx context.Context, id int64) (Course, error) {
	row := q.db.QueryRow(ctx, getCourseByIDForUpdate, id)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CategoryID,
		&i.Week,
		&i.Duration,
		&i.Capacity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password, created_at, updated_at, flag
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Flag,
	)
	return i, err
}

const getUserByIDForUpdate = `-- name: GetUserByIDForUpdate :one
SELECT id, username, password, created_at, updated_at, flag
FROM users
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetUserByIDForUpdate(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByIDForUpdate, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Flag,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password, created_at, updated_at, flag
FROM users
WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Flag,
	)
	return i, err
}

const incrementCapacity = `-- name: IncrementCapacity :one
UPDATE courses
SET
    capacity = capacity + 1,
    updated_at = NOW()
WHERE id = $1
RETURNING
    id,
    title,
    category_id,
    week,
    duration,
    capacity,
    created_at,
    updated_at
`

func (q *Queries) IncrementCapacity(ctx context.Context, id int64) (Course, error) {
	row := q.db.QueryRow(ctx, incrementCapacity, id)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CategoryID,
		&i.Week,
		&i.Duration,
		&i.Capacity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCourses = `-- name: ListCourses :many
SELECT
    id,
    title,
    category_id,
    week,
    duration,
    capacity,
    created_at,
    updated_at
FROM courses
`

func (q *Queries) ListCourses(ctx context.Context) ([]Course, error) {
	rows, err := q.db.Query(ctx, listCourses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Course
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CategoryID,
			&i.Week,
			&i.Duration,
			&i.Capacity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, password, created_at, updated_at, flag
FROM users
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Password,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Flag,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tryDecrementCapacity = `-- name: TryDecrementCapacity :one
UPDATE courses
SET
    capacity = capacity - 1,
    updated_at = NOW()
WHERE id = $1
  AND capacity > 0
RETURNING
    id,
    title,
    category_id,
    week,
    duration,
    capacity,
    created_at,
    updated_at
`

func (q *Queries) TryDecrementCapacity(ctx context.Context, id int64) (Course, error) {
	row := q.db.QueryRow(ctx, tryDecrementCapacity, id)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CategoryID,
		&i.Week,
		&i.Duration,
		&i.Capacity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCourse = `-- name: UpdateCourse :one
UPDATE courses
SET
    title = $2,
    category_id = $3,
    week = $4,
    duration = $5,
    capacity = $6,
    updated_at = NOW()
WHERE id = $1
RETURNING
    id,
    title,
    category_id,
    week,
    duration,
    capacity,
    created_at,
    updated_at
`

type UpdateCourseParams struct {
	ID         int64       `json:"id"`
	Title      string      `json:"title"`
	CategoryID int64       `json:"category_id"`
	Week       pgtype.Int4 `json:"week"`
	Duration   string      `json:"duration"`
	Capacity   int32       `json:"capacity"`
}

func (q *Queries) UpdateCourse(ctx context.Context, arg UpdateCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, updateCourse,
		arg.ID,
		arg.Title,
		arg.CategoryID,
		arg.Week,
		arg.Duration,
		arg.Capacity,
	)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CategoryID,
		&i.Week,
		&i.Duration,
		&i.Capacity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserFlag = `-- name: UpdateUserFlag :exec
UPDATE users
SET flag = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateUserFlagParams struct {
	ID   int64 `json:"id"`
	Flag int32 `json:"flag"`
}

func (q *Queries) UpdateUserFlag(ctx context.Context, arg UpdateUserFlagParams) error {
	_, err := q.db.Exec(ctx, updateUserFlag, arg.ID, arg.Flag)
	return err
}
